/**
 * Shared Iconoir icon adapter. Existing Passport names remain stable while the
 * exported components map each UI intent to its Iconoir equivalent.
 */
export {
	AppWindow,
	ArrowLeft,
	ArrowRight,
	AtSign,
	Bell,
	Building as Building2,
	Calendar as CalendarClock,
	Check,
	CheckCircle as CheckCircle2,
	Clock,
	ClockRotateRight as History,
	Code as FileJson,
	Computer as Monitor,
	Copy,
	CreditCard,
	Cpu as Bot,
	Drag as GripVertical,
	Dashboard as LayoutDashboard,
	Download,
	EditPencil as Pencil,
	Eye,
	EyeClosed as EyeOff,
	Fingerprint,
	FloppyDisk as Save,
	Globe,
	Globe as Globe2,
	Group as UsersRound,
	HalfMoon as Moon,
	HelpCircle as CircleHelp,
	HelpCircle,
	MediaImage as Image,
	Key as KeyRound,
	BookStack as Layers,
	Link,
	Link as Link2,
	Lock,
	Lock as LockKeyhole,
	LockSlash as Unlock,
	LogIn,
	LogOut,
	Mail,
	MailIn as MailPlus,
	MailOpen as MailCheck,
	Menu,
	NavArrowDown as ChevronDown,
	NavArrowRight as ChevronRight,
	Network,
	OpenNewWindow as ExternalLink,
	Package,
	Page as FileText,
	Page as Receipt,
	Page as ScrollText,
	PenTablet as Tablet,
	Phone,
	Phone as PhoneCall,
	Plus,
	Prohibition as Ban,
	QrCode,
	Refresh as RefreshCw,
	Repeat as Repeat2,
	Undo as RotateCcw,
	ScaleFrameEnlarge as Scale,
	Search,
	SearchEngine as SearchX,
	Send,
	Server as ServerCog,
	Settings,
	SettingsProfiles as UserCog,
	ShieldCheck,
	ShieldXmark as ShieldOff,
	ShieldXmark as ShieldX,
	Cart as ShoppingCart,
	MobileDevMode as Smartphone,
	StatsReport as Gauge,
	SunLight as Sun,
	TaskList as ListChecks,
	Trash as Trash2,
	Link as Unlink,
	Upload,
	User,
	User as UserRound,
	UserPlus,
	UserXmark as UserMinus,
	WarningTriangle as TriangleAlert,
	Network as Webhook,
	Xmark as X,
	XmarkCircle as XCircle,
} from "iconoir-react";
