/**
 * OAuth consent page. Inputs are the signed OAuth query string generated by
 * the Better Auth OAuth provider and the current Passport session; outputs are
 * a consent POST to `/oauth2/consent` and a browser redirect back to the client
 * with either an authorization code or an OAuth error.
 */
import { useEffect, useState, type ComponentType } from "react";
import {
	AtSign,
	Building2,
	Check,
	Clock,
	Fingerprint,
	Image,
	Link2,
	Mail,
	Phone,
	ShieldCheck,
	UserRound,
	UsersRound,
	X,
} from "lucide-react";

import { authClient } from "@/auth-client";
import { AuthShell } from "@/components/auth/auth-shell";
import { Wordmark } from "@/components/auth/wordmark";
import { StatusBanner, type Status } from "@/components/auth/status";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardFooter } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { useBrand } from "@/lib/brand-runtime";
import { cn } from "@/lib/utils";
import {
	OAUTH_CONSENT_ENDPOINT,
	oauthConsentRedirect,
	oauthConsentRequestBody,
} from "@/lib/oauth-consent";
import {
	OAUTH_SCOPE_DEFINITIONS,
	isSupportedOAuthScope,
	type SupportedOAuthScope,
} from "@/lib/oauth-scopes";
import { initialsOf } from "@/lib/session";

type ConsentClientMetadata = {
	clientId: string;
	name: string;
	uri?: string | null;
	icon?: string | null;
	tos?: string | null;
	policy?: string | null;
	disabled?: boolean;
};

type ConsentClientMetadataState = {
	clientId: string;
	loaded: boolean;
	client: ConsentClientMetadata | null;
};

/** Icons stay local to the React surface while scope copy comes from the shared registry. */
const SCOPE_ICONS: Record<SupportedOAuthScope, ComponentType<{ className?: string }>> = {
	openid: Fingerprint,
	profile: UserRound,
	email: Mail,
	phone: Phone,
	offline_access: Clock,
	"profile:picture": Image,
	"profile:username": AtSign,
	organizations: Building2,
	"organizations:ids": Building2,
	"organizations:roles": ShieldCheck,
	teams: UsersRound,
	"teams:ids": UsersRound,
	permissions: ShieldCheck,
	"account:security": Fingerprint,
	connections: Link2,
};

/** Past this many requested scopes the list wraps into two columns (and the card
 *  widens to suit) so the page does not require scrolling. */
const SCOPE_TWO_COLUMN_THRESHOLD = 6;

export function Consent() {
	const brand = useBrand();
	const { data: session, isPending: sessionPending } = authClient.useSession();
	const params = new URLSearchParams(window.location.search);
	const clientId = params.get("client_id") ?? "Unknown client";
	const scopes = (params.get("scope") ?? "openid profile email")
		.split(" ")
		.map((scope) => scope.trim())
		.filter(Boolean);
	const twoColumn = scopes.length > SCOPE_TWO_COLUMN_THRESHOLD;
	const consentWidth = twoColumn ? "md" : "sm";
	const [status, setStatus] = useState<Status | null>(null);
	const [loading, setLoading] = useState<"accept" | "deny" | null>(null);
	const [redirecting, setRedirecting] = useState(false);
	const [clientMetadataState, setClientMetadataState] = useState<ConsentClientMetadataState>({
		clientId: "",
		loaded: false,
		client: null,
	});
	const user = session?.user;
	const signedOut = !sessionPending && !session;
	const clientMetadataLoaded = clientMetadataState.clientId === clientId ? clientMetadataState.loaded : false;
	const clientMetadata = clientMetadataState.clientId === clientId ? clientMetadataState.client : null;
	const clientLabel = clientMetadata?.name ?? (clientMetadataLoaded ? "Unknown registered application" : "Loading application");
	const clientInitials = initialsOf(clientMetadata?.name ?? clientId);
	const clientLinks = [
		...(clientMetadata?.uri ? [{ label: "Website", href: clientMetadata.uri }] : []),
		...(clientMetadata?.tos ? [{ label: "Terms", href: clientMetadata.tos }] : []),
		...(clientMetadata?.policy ? [{ label: "Privacy", href: clientMetadata.policy }] : []),
	];
	const approvalBlocked = loading !== null || !clientMetadataLoaded || !clientMetadata || clientMetadata.disabled === true;

	useEffect(() => {
		let active = true;
		if (!clientId || clientId === "Unknown client") {
			queueMicrotask(() => {
				if (!active) return;
				setClientMetadataState({ clientId, loaded: true, client: null });
			});
			return () => {
				active = false;
			};
		}

		fetch(`/api/oauth/client-metadata?clientId=${encodeURIComponent(clientId)}`)
			.then(async (response) => {
				if (!active) return;
				if (!response.ok) {
					setClientMetadataState({ clientId, loaded: true, client: null });
					return;
				}
				const payload = (await response.json()) as { client?: ConsentClientMetadata };
				setClientMetadataState({ clientId, loaded: true, client: payload.client ?? null });
			})
			.catch(() => {
				if (!active) return;
				setClientMetadataState({ clientId, loaded: true, client: null });
			});

		return () => {
			active = false;
		};
	}, [clientId]);

	// Consent requires an authenticated visitor. Send signed-out users to
	// sign-in, preserving the full signed OAuth query so they return to this
	// consent screen once they finish.
	useEffect(() => {
		if (!signedOut) return;
		const callbackURL = window.location.pathname + window.location.search;
		window.location.assign(`/sign-in?callbackURL=${encodeURIComponent(callbackURL)}`);
	}, [signedOut]);

	async function decide(accept: boolean) {
		const body = oauthConsentRequestBody(window.location.search, accept);
		if (!body) {
			setStatus({ tone: "error", message: "Missing OAuth consent request." });
			return;
		}
		setLoading(accept ? "accept" : "deny");
		setStatus(null);
		const response = await fetch(OAUTH_CONSENT_ENDPOINT, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body),
		});

		if (!response.ok) {
			setLoading(null);
			setStatus({ tone: "error", message: await response.text() });
			return;
		}

		const payload = (await response.json()) as {
			redirect_uri?: string;
			redirectURI?: string;
			redirectTo?: string;
			url?: string;
		};
		const redirect = oauthConsentRedirect(payload);
		if (redirect) {
			// Paint the redirecting hand-off for a frame before the browser
			// leaves so the transition does not flash an empty card.
			setRedirecting(true);
			requestAnimationFrame(() => window.location.assign(redirect));
			return;
		}
		setLoading(null);
		setStatus({
			tone: "error",
			message: "Consent was accepted but no redirect URL was returned.",
		});
	}

	// Hold the skeleton until the session resolves (and through the redirect
	// hand-off for signed-out visitors) so the consent card never flashes to
	// someone who is about to be sent to sign-in.
	if (!clientMetadataLoaded || sessionPending || signedOut) {
		return (
			<AuthShell width={consentWidth}>
				<ConsentSkeleton scopeCount={scopes.length} twoColumn={twoColumn} />
			</AuthShell>
		);
	}

	if (redirecting) {
		return (
			<AuthShell width={consentWidth}>
				<Card className="w-full overflow-hidden">
					<CardContent className="flex flex-col items-center gap-5 px-6 py-12 text-center">
						<Handshake
							clientMetadata={clientMetadata}
							clientInitials={clientInitials}
							active
						/>
						<div className="space-y-1">
							<p className="text-sm font-medium">Redirecting…</p>
							<p className="text-sm text-muted-foreground">
								Taking you back to{" "}
								<span className="font-medium text-foreground">{clientLabel}</span>.
							</p>
						</div>
					</CardContent>
				</Card>
			</AuthShell>
		);
	}

	return (
		<AuthShell width={consentWidth}>
			<div className="flex flex-col items-center gap-6">
				<Card className="w-full gap-0 overflow-hidden py-0">
					<CardContent className="space-y-5 px-6 pt-6 pb-5">
						{/* Brand ↔ client handshake. */}
						<Handshake clientMetadata={clientMetadata} clientInitials={clientInitials} />

						<div className="space-y-1 text-center">
							<h1 className="text-lg font-semibold tracking-tight">Authorize access</h1>
							<p className="text-sm text-muted-foreground">
								<span className="font-medium text-foreground">{clientLabel}</span> wants to access your{" "}
								{brand.name} account.
							</p>
							<p className="font-mono text-xs text-muted-foreground">{clientId}</p>
							{clientLinks.length ? (
								<div className="flex flex-wrap justify-center gap-2 pt-1">
									{clientLinks.map((link) => (
										<a
											key={link.label}
											href={link.href}
											target="_blank"
											rel="noreferrer"
											className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground"
										>
											<Link2 className="size-3" />
											{link.label}
										</a>
									))}
								</div>
							) : null}
						</div>

						<StatusBanner status={status} />

						{clientMetadata?.disabled ? (
							<StatusBanner
								status={{
									tone: "error",
									message: "This application is disabled and cannot be approved.",
								}}
							/>
						) : null}

						{user ? (
							<div className="flex items-center gap-2.5 rounded-lg border bg-muted/30 px-3 py-2.5">
								<span className="grid size-7 shrink-0 place-items-center overflow-hidden rounded-full border bg-background text-[0.6875rem] font-medium">
									{user.image ? (
										<img src={user.image} alt="" className="size-full object-cover" />
									) : (
										initialsOf(user.name)
									)}
								</span>
								<div className="min-w-0 flex-1 text-sm">
									<span className="text-muted-foreground">Signed in as </span>
									<span className="font-medium">{user.email}</span>
								</div>
							</div>
						) : null}

						<div className="space-y-2">
							<div className="text-xs font-medium text-muted-foreground">This will allow it to</div>
							<ul className={cn("gap-px", twoColumn ? "grid grid-cols-2 gap-x-3" : "flex flex-col")}>
								{scopes.map((scope) => {
									const definition = isSupportedOAuthScope(scope)
										? OAUTH_SCOPE_DEFINITIONS[scope]
										: undefined;
									const Icon = definition ? SCOPE_ICONS[definition.scope] : Check;
									return (
										<li
											key={scope}
											className="flex items-center gap-3 rounded-lg px-2 py-2 transition-colors hover:bg-muted/40"
										>
											<span className="grid size-8 shrink-0 place-items-center rounded-lg border bg-background text-muted-foreground">
												<Icon className="size-4" />
											</span>
											{twoColumn ? (
												<span className="min-w-0 flex-1">
													<span className="block truncate text-sm">{definition?.consent ?? scope}</span>
													<span className="block truncate font-mono text-[0.6875rem] text-muted-foreground">
														{scope}
													</span>
												</span>
											) : (
												<>
													<span className="flex-1 text-sm">{definition?.consent ?? scope}</span>
													<span className="font-mono text-[0.6875rem] text-muted-foreground">{scope}</span>
												</>
											)}
										</li>
									);
								})}
							</ul>
						</div>
					</CardContent>

					<CardFooter className="flex-col gap-3 border-t bg-muted/40 px-6 py-4">
						<div className="grid w-full grid-cols-2 gap-2">
							<Button variant="outline" onClick={() => decide(false)} disabled={loading !== null}>
								<X className="size-4" />
								Deny
							</Button>
							<Button autoFocus onClick={() => decide(true)} disabled={approvalBlocked}>
								<Check className="size-4" />
								{loading === "accept" ? "Authorizing…" : "Allow"}
							</Button>
						</div>
						<p className="flex items-center gap-1.5 text-center text-xs text-muted-foreground">
							<ShieldCheck className="size-3.5" />
							You can revoke this access anytime from Applications.
						</p>
					</CardFooter>
				</Card>
			</div>
		</AuthShell>
	);
}

/** Brand → client mark pair joined by an animated connector. `active` speeds the
 *  travelling pulse for the redirecting hand-off. */
function Handshake({
	clientMetadata,
	clientInitials,
	active,
}: {
	clientMetadata: ConsentClientMetadata | null;
	clientInitials: string;
	active?: boolean;
}) {
	return (
		<div className="flex items-center justify-center gap-3">
			<Wordmark className="consent-mark h-9" />
			<div
				className="consent-connector"
				data-active={active ? "true" : undefined}
				aria-hidden="true"
			/>
			{clientMetadata?.icon ? (
				<img
					src={clientMetadata.icon}
					alt=""
					className="consent-mark consent-mark-client size-11 rounded-xl border bg-muted/40 object-cover"
				/>
			) : (
				<div className="consent-mark consent-mark-client grid size-11 place-items-center rounded-xl border bg-muted/40 text-sm font-semibold text-muted-foreground">
					{clientInitials}
				</div>
			)}
		</div>
	);
}

/** Placeholder card shown while client metadata resolves, mirroring the real
 *  layout so the swap does not shift. */
function ConsentSkeleton({ scopeCount, twoColumn }: { scopeCount: number; twoColumn: boolean }) {
	const rows = Math.min(Math.max(scopeCount, 1), twoColumn ? 16 : 6);
	return (
		<div className="flex flex-col items-center gap-6">
			<Card className="w-full gap-0 overflow-hidden py-0">
				<CardContent className="space-y-5 px-6 pt-6 pb-5">
					<div className="flex items-center justify-center gap-3">
						<Skeleton className="size-11 rounded-xl" />
						<div className="consent-connector" aria-hidden="true" />
						<Skeleton className="size-11 rounded-xl" />
					</div>
					<div className="flex flex-col items-center gap-2">
						<Skeleton className="h-5 w-40" />
						<Skeleton className="h-4 w-56" />
						<Skeleton className="h-3 w-32" />
					</div>
					<div className="space-y-2">
						<Skeleton className="h-3 w-28" />
						<div className={cn("gap-1", twoColumn ? "grid grid-cols-2 gap-x-3" : "flex flex-col")}>
							{Array.from({ length: rows }).map((_, index) => (
								<div key={index} className="flex items-center gap-3 px-2 py-2">
									<Skeleton className="size-8 shrink-0 rounded-lg" />
									<Skeleton className="h-4 flex-1" />
								</div>
							))}
						</div>
					</div>
				</CardContent>
				<CardFooter className="flex-col gap-3 border-t bg-muted/40 px-6 py-4">
					<div className="grid w-full grid-cols-2 gap-2">
						<Skeleton className="h-9" />
						<Skeleton className="h-9" />
					</div>
					<Skeleton className="h-3 w-56" />
				</CardFooter>
			</Card>
		</div>
	);
}
