/**
 * OAuth consent page. Inputs are the signed OAuth query string generated by
 * the Better Auth OAuth provider and the current Passport session; outputs are
 * a consent POST to `/oauth2/consent` and a browser redirect back to the client
 * with either an authorization code or an OAuth error.
 */
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState, type ComponentType } from "react";
import {
	AtSign,
	ArrowRight,
	Building2,
	Check,
	Clock,
	CreditCard,
	ExternalLink,
	Fingerprint,
	Gauge,
	Globe2,
	Image,
	ListChecks,
	Link2,
	Mail,
	Phone,
	Receipt,
	Repeat2,
	ScrollText,
	ShieldCheck,
	UserRound,
	UsersRound,
	X,
} from "lucide-react";

import { authClient } from "@/auth-client";
import { AuthShell } from "@/components/auth/auth-shell";
import { Wordmark } from "@/components/auth/wordmark";
import { StatusBanner, type Status } from "@/components/auth/status";
import { Button } from "@/components/kumo/primitives/button";
import { Card, CardContent, CardFooter } from "@/components/kumo/primitives/card";
import { Skeleton } from "@/components/kumo/primitives/skeleton";
import { Loader } from "@/components/kumo/primitives/loader";
import { useBrand } from "@/lib/brand-runtime";
import { fetchAPIJSON, queryKeys } from "@/lib/query-client";
import { cn } from "@/lib/utils";
import {
	OAUTH_CONSENT_ENDPOINT,
	oauthConsentRedirect,
	oauthConsentRequestBody,
} from "@/lib/oauth-consent";
import {
	OAUTH_SCOPE_DEFINITIONS,
	isSupportedOAuthScope,
	oauthScopeConsentText,
	type SupportedOAuthScope,
} from "@/lib/oauth-scopes";
import { initialsOf } from "@/lib/session";

type ConsentClientMetadata = {
	clientId: string;
	name: string;
	uri?: string | null;
	icon?: string | null;
	tos?: string | null;
	policy?: string | null;
	disabled?: boolean;
	createdAt?: string | null;
};

/** A same-browser account session that can become the OAuth authorization subject. */
/** Icons stay local to the React surface while scope copy comes from the shared registry. */
const SCOPE_ICONS: Record<SupportedOAuthScope, ComponentType<{ className?: string }>> = {
	openid: Fingerprint,
	profile: UserRound,
	email: Mail,
	phone: Phone,
	offline_access: Clock,
	"profile:picture": Image,
	"profile:username": AtSign,
	"profile:write": UserRound,
	organizations: Building2,
	"organizations:ids": Building2,
	"organizations:roles": ShieldCheck,
	"organizations:write": Building2,
	"organization-invitations:read": Mail,
	"organization-invitations:write": Mail,
	"organization-members:read": UsersRound,
	"organization-members:write": UsersRound,
	teams: UsersRound,
	"teams:ids": UsersRound,
	"teams:write": UsersRound,
	"team-members:read": UsersRound,
	"team-members:write": UsersRound,
	permissions: ShieldCheck,
	"account:security": Fingerprint,
	connections: Link2,
	"billing:status": CreditCard,
	"billing:subscriptions": ListChecks,
	"billing:purchases": Receipt,
	"billing:entitlements": ShieldCheck,
	"billing:limits": Gauge,
	"billing:checkout": CreditCard,
	"billing:manage": CreditCard,
};

/** Past this many requested scopes the list wraps into two columns (and the card
 *  widens to suit) so the page does not require scrolling. */
const SCOPE_TWO_COLUMN_THRESHOLD = 6;

export function Consent() {
	const brand = useBrand();
	const { data: session, isPending: sessionPending } = authClient.useSession();
	const params = new URLSearchParams(window.location.search);
	const clientId = params.get("client_id") ?? "Unknown client";
	const scopes = (params.get("scope") ?? "openid profile email")
		.split(" ")
		.map((scope) => scope.trim())
		.filter(Boolean);
	const twoColumn = scopes.length > SCOPE_TWO_COLUMN_THRESHOLD;
	const consentWidth = twoColumn ? "md" : "sm";
	const [status, setStatus] = useState<Status | null>(null);
	const [loading, setLoading] = useState<"accept" | "deny" | null>(null);
	const [redirecting, setRedirecting] = useState(false);
	const hasClientId = Boolean(clientId && clientId !== "Unknown client");
	const clientMetadataQuery = useQuery({
		queryKey: queryKeys.consentClientMetadata(clientId),
		queryFn: async () => {
			try {
				const payload = await fetchAPIJSON<{ client?: ConsentClientMetadata }>(
					`/api/oauth/client-metadata?clientId=${encodeURIComponent(clientId)}`,
				);
				return payload.client ?? null;
			} catch {
				return null;
			}
		},
		enabled: hasClientId,
	});
	const user = session?.user;
	const signedOut = !sessionPending && !session;
	const clientMetadataLoaded = hasClientId ? clientMetadataQuery.isFetched : true;
	const clientMetadata = hasClientId ? clientMetadataQuery.data ?? null : null;
	const clientLabel = clientMetadata?.name ?? (clientMetadataLoaded ? "Unknown Application" : "Loading application");
	const clientInitials = initialsOf(clientMetadata?.name ?? clientId);
	const clientLinks = [
		...(clientMetadata?.uri ? [{ label: "Website", href: clientMetadata.uri, icon: Globe2 }] : []),
		...(clientMetadata?.tos ? [{ label: "Terms", href: clientMetadata.tos, icon: ScrollText }] : []),
		...(clientMetadata?.policy ? [{ label: "Privacy", href: clientMetadata.policy, icon: ShieldCheck }] : []),
	];
	const accountSelectionURL = `/select-account?${params.toString()}`;
	const clientAge = applicationAge(clientMetadata?.createdAt);
	const approvalBlocked = loading !== null || !clientMetadataLoaded || !clientMetadata || clientMetadata.disabled === true;

	// Consent requires an authenticated visitor. Send signed-out users to
	// sign-in, preserving the full signed OAuth query so they return to this
	// consent screen once they finish.
	useEffect(() => {
		if (!signedOut) return;
		const callbackURL = window.location.pathname + window.location.search;
		window.location.assign(`/sign-in?callbackURL=${encodeURIComponent(callbackURL)}`);
	}, [signedOut]);

	async function decide(accept: boolean) {
		const body = oauthConsentRequestBody(window.location.search, accept);
		if (!body) {
			setStatus({ tone: "error", message: "Missing OAuth consent request." });
			return;
		}
		setLoading(accept ? "accept" : "deny");
		setStatus(null);
		const response = await fetch(OAUTH_CONSENT_ENDPOINT, {
			method: "POST",
			headers: { "content-type": "application/json" },
			body: JSON.stringify(body),
		});

		if (!response.ok) {
			setLoading(null);
			setStatus({ tone: "error", message: await response.text() });
			return;
		}

		const payload = (await response.json()) as {
			redirect_uri?: string;
			redirectURI?: string;
			redirectTo?: string;
			url?: string;
		};
		const redirect = oauthConsentRedirect(payload);
		if (redirect) {
			// Paint the redirecting hand-off for a frame before the browser
			// leaves so the transition does not flash an empty card.
			setRedirecting(true);
			requestAnimationFrame(() => window.location.assign(redirect));
			return;
		}
		setLoading(null);
		setStatus({
			tone: "error",
			message: "Consent was accepted but no redirect URL was returned.",
		});
	}

	// Hold the skeleton until the session resolves (and through the redirect
	// hand-off for signed-out visitors) so the consent card never flashes to
	// someone who is about to be sent to sign-in.
	if (!clientMetadataLoaded || sessionPending || signedOut) {
		return (
			<AuthShell width={consentWidth}>
				<ConsentSkeleton scopeCount={scopes.length} twoColumn={twoColumn} />
			</AuthShell>
		);
	}

	if (redirecting) {
		return (
			<AuthShell width={consentWidth}>
				<Card className="w-full overflow-hidden">
					<CardContent className="flex flex-col items-center gap-5 px-6 py-12 text-center">
						<Handshake
							clientMetadata={clientMetadata}
							clientInitials={clientInitials}
						/>
						<div className="space-y-1">
							<p className="text-sm font-medium">Redirecting…</p>
							<p className="text-sm text-muted-foreground">
								Taking you back to{" "}
								<span className="font-medium text-foreground">{clientLabel}</span>.
							</p>
						</div>
					</CardContent>
				</Card>
			</AuthShell>
		);
	}

	return (
		<AuthShell width={consentWidth}>
			<div className="flex flex-col items-center gap-6">
				<Card className="w-full gap-0 overflow-hidden py-0">
					<CardContent className="space-y-5 px-6 pt-6 pb-5">
						{/* Brand ↔ client handshake. */}
						<Handshake clientMetadata={clientMetadata} clientInitials={clientInitials} />

						<div className="space-y-1 text-center">
							<h1 className="text-lg font-semibold tracking-tight">Authorize access</h1>
							<p className="text-sm text-muted-foreground">
								<span className="font-medium text-foreground">{clientLabel}</span> wants to access your{" "}
								{brand.name} account.
							</p>
							{clientAge ? <p className="text-xs text-muted-foreground">Registered {clientAge}</p> : null}
							{clientLinks.length ? (
								<div className="flex flex-wrap justify-center gap-2 pt-1">
									{clientLinks.map((link) => {
										const Icon = link.icon;
										return (
											<a
											key={link.label}
											href={link.href}
											target="_blank"
											rel="noreferrer"
											className="inline-flex items-center gap-1 text-xs font-medium text-muted-foreground hover:text-foreground"
										>
												<Icon className="size-3" />
											{link.label}
											<ExternalLink className="size-3" />
											</a>
										);
									})}
								</div>
							) : null}
						</div>

						<StatusBanner status={status} />

						{clientMetadata?.disabled ? (
							<StatusBanner
								status={{
									tone: "error",
									message: "This application is disabled and cannot be approved.",
								}}
							/>
						) : null}

						{user ? (
							<div className="flex items-center gap-2.5 rounded-lg border bg-muted/30 px-3 py-2.5">
								<span className="grid size-7 shrink-0 place-items-center overflow-hidden rounded-full border bg-background text-[0.6875rem] font-medium">
									{user.image ? (
										<img
											src={user.image}
											alt=""
											className="size-full object-cover outline outline-1 -outline-offset-1 outline-black/10 dark:outline-white/10"
										/>
									) : (
										initialsOf(user.name)
									)}
								</span>
								<div className="min-w-0 flex-1 text-sm">
									<span className="text-muted-foreground">Signed in as </span>
									<span className="font-medium">{user.email}</span>
								</div>
								<Button asChild size="sm" variant="outline">
									<a href={accountSelectionURL}>
										<Repeat2 className="size-3.5" />
										Switch account
									</a>
								</Button>
							</div>
						) : null}

						<div className="space-y-2">
							<div className="text-xs font-medium text-muted-foreground">This will allow it to</div>
							<ul className={cn("gap-px", twoColumn ? "grid grid-cols-2 gap-x-3" : "flex flex-col")}>
								{scopes.map((scope) => {
									const definition = isSupportedOAuthScope(scope)
										? OAUTH_SCOPE_DEFINITIONS[scope]
										: undefined;
									const consentText = oauthScopeConsentText(scope);
									const Icon = definition ? SCOPE_ICONS[definition.scope] : Check;
									return (
										<li
											key={scope}
										className="flex items-start gap-3 rounded-lg px-2 py-2 transition-colors hover:bg-muted/40"
										>
											<span className="grid size-8 shrink-0 place-items-center rounded-lg border bg-background text-muted-foreground">
												<Icon className="size-4" />
											</span>
											{twoColumn ? (
											<span className="min-w-0 flex-1">
												<span className="block text-sm leading-snug">{consentText}</span>
												<span className="mt-0.5 block break-all font-mono text-[0.6875rem] text-muted-foreground">
														{scope}
													</span>
												</span>
											) : (
												<>
											<span className="min-w-0 flex-1 text-sm leading-snug">{consentText}</span>
											<span className="max-w-28 break-all text-right font-mono text-[0.6875rem] text-muted-foreground">{scope}</span>
												</>
											)}
										</li>
									);
								})}
							</ul>
						</div>
					</CardContent>

					<CardFooter className="flex-col gap-3 border-t bg-muted/40 px-6 py-4">
						<div className="flex w-full justify-center gap-2">
							<Button size="lg" variant="outline" onClick={() => decide(false)} disabled={loading !== null}>
								<X className="size-4" />
								Deny
							</Button>
								<Button size="lg" autoFocus onClick={() => decide(true)} disabled={approvalBlocked}>
									{loading === "accept" ? (
										<Loader size="sm" className="text-primary-foreground" />
									) : (
										<>
											<Check className="size-4" />
											Allow
										</>
									)}
								</Button>
						</div>
						<div className="space-y-1 text-center text-xs leading-relaxed text-muted-foreground">
							<p>You can revoke this access at any time from Applications.</p>
							<p>{clientLabel} cannot access your password.</p>
						</div>
					</CardFooter>
				</Card>
			</div>
		</AuthShell>
	);
}

/** Returns a concise, stable age label for a client registration timestamp. */
function applicationAge(createdAt: string | null | undefined) {
	if (!createdAt) return undefined;
	const timestamp = new Date(createdAt).getTime();
	if (Number.isNaN(timestamp)) return undefined;
	const days = Math.max(0, Math.floor((Date.now() - timestamp) / 86_400_000));
	if (days < 1) return "today";
	if (days < 30) return `${days} day${days === 1 ? "" : "s"} ago`;
	const months = Math.floor(days / 30);
	if (months < 12) return `${months} month${months === 1 ? "" : "s"} ago`;
	const years = Math.floor(days / 365);
	return `${years} year${years === 1 ? "" : "s"} ago`;
}

/** Brand and client marks use a quiet direction marker instead of a travelling pulse. */
function Handshake({
	clientMetadata,
	clientInitials,
}: {
	clientMetadata: ConsentClientMetadata | null;
	clientInitials: string;
}) {
	return (
		<div className="flex items-center justify-center gap-3">
			<Wordmark className="consent-mark h-9" />
			<span className="consent-direction grid size-7 place-items-center rounded-full border bg-muted/40 text-muted-foreground" aria-hidden="true">
				<ArrowRight className="size-3.5" />
			</span>
			{clientMetadata?.icon ? (
				<img
					src={clientMetadata.icon}
					alt=""
					className="consent-mark consent-mark-client size-11 rounded-xl bg-muted/40 object-cover outline outline-1 -outline-offset-1 outline-black/10 dark:outline-white/10"
				/>
			) : (
				<div className="consent-mark consent-mark-client grid size-11 place-items-center rounded-xl border bg-muted/40 text-sm font-semibold text-muted-foreground">
					{clientInitials}
				</div>
			)}
		</div>
	);
}

/** Placeholder card shown while client metadata resolves, mirroring the real
 *  layout so the swap does not shift. */
function ConsentSkeleton({ scopeCount, twoColumn }: { scopeCount: number; twoColumn: boolean }) {
	const rows = Math.min(Math.max(scopeCount, 1), twoColumn ? 16 : 6);
	return (
		<div className="flex flex-col items-center gap-6">
			<Card className="w-full gap-0 overflow-hidden py-0">
					<CardContent className="space-y-5 px-6 pt-6 pb-5">
						<div className="flex items-center justify-center gap-3">
							<Skeleton className="size-11 rounded-xl" />
							<Skeleton className="h-1 w-11 rounded-full" />
							<Skeleton className="size-11 rounded-xl" />
						</div>
					<div className="flex flex-col items-center gap-2">
						<Skeleton className="h-5 w-40" />
						<Skeleton className="h-4 w-56" />
						<Skeleton className="h-3 w-32" />
					</div>
					<div className="space-y-2">
						<Skeleton className="h-3 w-28" />
						<div className={cn("gap-1", twoColumn ? "grid grid-cols-2 gap-x-3" : "flex flex-col")}>
							{Array.from({ length: rows }).map((_, index) => (
								<div key={index} className="flex items-center gap-3 px-2 py-2">
									<Skeleton className="size-8 shrink-0 rounded-lg" />
									<Skeleton className="h-4 flex-1" />
								</div>
							))}
						</div>
					</div>
				</CardContent>
				<CardFooter className="flex-col gap-3 border-t bg-muted/40 px-6 py-4">
					<div className="grid w-full grid-cols-2 gap-2">
						<Skeleton className="h-9" />
						<Skeleton className="h-9" />
					</div>
					<Skeleton className="h-3 w-56" />
				</CardFooter>
			</Card>
		</div>
	);
}
